# Generated by Django 3.1.2 on 2020-11-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('about', models.TextField(max_length=2048)),
                ('max_student', models.IntegerField(default=15)),
                ('is_evening_group', models.BooleanField(default=True)),
            ],
        ),
    ]
